# Hadolint configuration for Dockerfile linting

ignored:
  # DL3008: We use Debian stable (bookworm) which provides stable package versions.
  # Pinning individual apt packages makes Dockerfiles brittle and prevents security updates.
  - DL3008
  # DL3013: Utility containers (metadata-service, visualizer, fb-display) use simple
  # pip installs. Pinning adds brittleness for no security benefit on these internal services.
  - DL3013
