# Hadolint configuration for Dockerfile linting

ignored:
  # DL3008: We use Debian stable (bookworm) which provides stable package versions.
  # Pinning individual apt packages makes Dockerfiles brittle and prevents security updates.
  # The snapcast version is already pinned (v0.33.0 in git clone).
  - DL3008
